sudo: false

language: node_js
node_js:
  - "10"
  - "9"
  - "8"

before_script:
  - npm install

script:
  - npm run build
  - npm run node-test

before_deploy:
  - mkdir -p piexifjs/dist
  - cp ./dist/piexif.js ./piexifjs/dist
  - cp ./dist/piexif.js.map ./piexifjs/dist
  - cp ./dist/index.d.ts ./piexifjs/dist
  - cp ./README.md ./piexifjs/
  - cp ./package.json ./piexifjs/
  - cp ./LICENSE.txt ./piexifjs/
  - zip -r piexifjs.zip ./piexifjs
  - rm -rf piexifjs
deploy:
  - provider: releases
    api_key: "${GITHUB_OAUTH_TOKEN}"
    file: piexifjs.zip
    skip_cleanup: true
    on:
      tags: true
  - provider: npm
    email: "${NPM_MYMAIL}"
    api_key: "${NPM_TOKEN}"
    skip_cleanup: true
    tag: beta
    on:
      tags: true
      condition: $TRAVIS_NODE_VERSION = 10
